In [2]:
import pandas as pd
import numpy as np
import time
import datetime
from datetime import datetime as dt
import re

In [33]:
df = pd.DataFrame()
y = 55
timeGame = list()
team1Name = list()
team1Score = list()
team2Score = list()
team2Name = list()
team1Odds = list()
team2Odds = list()
while y > 0:
    fp = open('pages/page{}.txt'.format(y), 'r')
    lines = fp.readlines()

    x = 0



    while x < 360:
        try:
            timeGame.append(lines[x].strip())
            x += 1
            team1Name.append(lines[x].strip())
            x += 1
            team1Score.append(lines[x].strip())
            x += 2
            team2Score.append(lines[x].strip())
            x += 1
            team2Name.append(lines[x].strip())
            x += 1
            team1Odds.append(lines[x].strip())
            x += 1
            team2Odds.append(lines[x].strip())
            x += 2
        except:
            break
    fp.close()
    y -= 1

df['timeGame'] = timeGame
df['team1Name'] = team1Name
df['team1Score'] = team1Score
df['team1Odds'] = team1Odds
df['team2Name'] = team2Name
df['team2Score'] = team2Score
df['team2Odds'] = team2Odds

df

,timeGame,team1Name,team1Score,team1Odds,team2Name,team2Score,team2Odds
0,16:05,Chicago Cubs,5,1.66,Oakland Athletics,4,2.15
1,16:05,Los Angeles Dodgers,6,1.55,Cleveland Guardians,2,2.36
2,16:05,San Francisco Giants,3,1.53,Arizona Diamondbacks,5,2.41
3,16:05,Texas Rangers,14,2.20,Chicago White Sox,5,1.64
4,13:05,Atlanta Braves,7,1.78,Tampa Bay Rays,7,1.98
...,...,...,...,...,...,...,...
2151,20:03,Houston Astros,5,1.61,Philadelphia Phillies,6,2.42
2152,19:07,New York Yankees,5,1.83,Houston Astros,6,2.05
2153,14:37,Philadelphia Phillies,4,1.72,San Diego Padres,3,2.20
2154,19:45,Philadelphia Phillies,10,1.89,San Diego Padres,6,1.96
2155,17:07,New York Yankees,0,1.69,Houston Astros,5,2.26

In [34]:
df.to_csv('mlb_odds_data_2022.csv')

In [32]:
teams = {
        "Chicage White Sox": None,
        "Cleveland Gaurdians": None,
        "Detroit Tigers": None,
        "Kansas City Royals": None,
        "Minnesota Twins": None,
        "Baltimore Orioles": None,
        "Boston Red Sox": None,
        "New York Yankees": None,
        "Tampa Bay Rays": None,
        "Toronto Blue Jays": None,
        "Houston Astros": None,
        "Los Angeles Angels": None,
        "Oakland Athletics": None,
        "Seattle Mariners": None,
        "Texas Rangers": None,
        "Chicago Clubs": None,
        "Cincinnati Reds": None,
        "Milwaukee Brewers": None,
        "Pittsburgh Pirates": None,
        "St. Louis Cardinals": None,
        "Atlanta Braves": None,
        "Miami Marlins": None,
        "New York Mets": None,
        "Philadelphia Phillies": None,
        "Washington Nationals": None,
        "Arizona Diamondbacks": None,
        "Colorado Rockies": None,
        "Los Angeles Dogers": None,
        "San Diego Padres": None,
        "San Francisco Giants": None
}
names = list()
for x in teams.keys():
    names.append(x)

print(names)

['Chicage White Sox', 'Cleveland Gaurdians', 'Detroit Tigers', 'Kansas City Royals', 'Minnesota Twins', 'Baltimore Orioles', 'Boston Red Sox', 'New York Yankees', 'Tampa Bay Rays', 'Toronto Blue Jays', 'Houston Astros', 'Los Angeles Angels', 'Oakland Athletics', 'Seattle Mariners', 'Texas Rangers', 'Chicago Clubs', 'Cincinnati Reds', 'Milwaukee Brewers', 'Pittsburgh Pirates', 'St. Louis Cardinals', 'Atlanta Braves', 'Miami Marlins', 'New York Mets', 'Philadelphia Phillies', 'Washington Nationals', 'Arizona Diamondbacks', 'Colorado Rockies', 'Los Angeles Dogers', 'San Diego Padres', 'San Francisco Giants']