In [3]:
import pandas as pd
import numpy as np
from RefrenceDict import teams
import json

# insert file.csv into dataframe
df = pd.read_csv('mlb_odds_data_2022.csv', index_col=0)
df.head()

result = []
winningOdds = []
for tm1, tm2, sc1, sc2, od1, od2 in zip(df['team1Name'], df['team2Name'], df['team1Score'], df['team2Score'], df['team1Odds'], df['team2Odds']):
    if (sc1 > sc2):
        result.append(tm1)
        winningOdds.append(od1)
    else:
        result.append(tm2)
        winningOdds.append(od2)
df['result'] = result
df['winningOdds'] = winningOdds

,timeGame,team1Name,team1Score,team1Odds,team2Name,team2Score,team2Odds,result,winningOdds
0,16:05,Chicago Cubs,5,1.66,Oakland Athletics,4,2.15,Chicago Cubs,1.66
1,16:05,Los Angeles Dodgers,6,1.55,Cleveland Guardians,2,2.36,Los Angeles Dodgers,1.55
2,16:05,San Francisco Giants,3,1.53,Arizona Diamondbacks,5,2.41,Arizona Diamondbacks,2.41
3,16:05,Texas Rangers,14,2.20,Chicago White Sox,5,1.64,Texas Rangers,2.20
4,13:05,Atlanta Braves,7,1.78,Tampa Bay Rays,7,1.98,Tampa Bay Rays,1.98