In [60]:
import pandas as pd
import datetime
from datetime import datetime as dt
from datetime import date
import matplotlib.pyplot as plt

df = pd.read_csv("data/mlb_2022_season_data.csv", index_col=0)

# win / loss = df1
sdate = date(2022, 3, 30)
edate = date(2022, 7, 10)
df1 = pd.DataFrame()

while True:
    if (sdate > edate): 
        break
    sDate = sdate.strftime('%Y-%m-%d')
    df1[f'+/- ({sDate})'] = df[f'+/- ({sDate})']
    sdate = sdate + datetime.timedelta(days = 1)

df1.index.name = 'team'


# points scored = df3
sdate = date(2022, 3, 30)
edate = date(2022, 7, 10)
df3 = pd.DataFrame()

while True:
    if (sdate > edate): 
        break
    sDate = sdate.strftime('%Y-%m-%d')
    df3[f'points scored ({sDate})'] = df[f'points scored ({sDate})']
    sdate = sdate + datetime.timedelta(days = 1)

df3.index.name = 'team'





# win / loss cummulative sum = df2
sdate = date(2022, 3, 30)
edate = date(2022, 7, 10)
df2 = pd.DataFrame()
df2 = df1.cumsum(axis=1)

while True:
    if (sdate > edate): 
        break
    sDate = sdate.strftime('%Y-%m-%d')
    df[f'+/- ({sDate})'] = df2[f'+/- ({sDate})']
    sdate = sdate + datetime.timedelta(days = 1)



# points scored cummulative sum = df4
sdate = date(2022, 3, 30)
edate = date(2022, 7, 10)
df4 = pd.DataFrame()
df4 = df3.cumsum(axis=1)

while True:
    if (sdate > edate): 
        break
    sDate = sdate.strftime('%Y-%m-%d')
    df[f'points scored ({sDate})'] = df4[f'points scored ({sDate})']
    sdate = sdate + datetime.timedelta(days = 1)

df

/var/folders/yf/7gfkdn91637dg1_hrqhwtgkr0000gn/T/ipykernel_36380/460988060.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df1[f'+/- ({sDate})'] = df[f'+/- ({sDate})']
/var/folders/yf/7gfkdn91637dg1_hrqhwtgkr0000gn/T/ipykernel_36380/460988060.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df1[f'+/- ({sDate})'] = df[f'+/- ({sDate})']
/var/folders/yf/7gfkdn91637dg1_hrqhwtgkr0000gn/T/ipykernel_36380/460988060.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df1[f'+/- ({sDate})'] = df[f'+/- ({sDate})']
/var/folders/yf/7gfkdn91637dg1_hrqhwtgkr0000gn/T/ipykernel_36380/460988060.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df3[f'points scored ({sDate})'] = df[f'points scored ({sDate})']
/var/folders/yf/7gfkdn91637dg1_hrqhwtgkr0000gn/T/ipykernel_36380/460988060.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df3[f'points scored ({sDate})'] = df[f'points scored ({sDate})']
/var/folders/yf/7gfkdn91637dg1_hrqhwtgkr0000gn/T/ipykernel_36380/460988060.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df3[f'points scored ({sDate})'] = df[f'points scored ({sDate})']

,opponent (2022-03-30),points scored (2022-03-30),+/- (2022-03-30),opponent (2022-03-31),points scored (2022-03-31),+/- (2022-03-31),opponent (2022-04-01),points scored (2022-04-01),+/- (2022-04-01),opponent (2022-04-02),...,+/- (2022-07-07),opponent (2022-07-08),points scored (2022-07-08),+/- (2022-07-08),opponent (2022-07-09),points scored (2022-07-09),+/- (2022-07-09),opponent (2022-07-10),points scored (2022-07-10),+/- (2022-07-10)
WSH,STL,29,-1,NYM,36,0,NaN,36,0,NaN,...,-25,ATL,627,-26,ATL,631,-27,ATL,635,-28
TEX,CWS,7,-1,LAD,15,0,SF,22,1,CLE,...,-5,MIN,526,-4,MIN,535,-3,MIN,541,-4
BOS,ATL,10,1,MIN,14,2,TB,23,1,PIT,...,7,NYY,566,6,NYY,572,7,NYY,583,8
OAK,CIN,5,1,KC,10,0,CWS,22,1,COL,...,-29,HOU,510,-30,HOU,513,-29,HOU,519,-30
CHC,SEA,8,1,NaN,8,1,MIL,13,0,LAA,...,-12,LAD,595,-13,LAD,599,-14,LAD,610,-15
NYY,TOR,11,-1,PHI,16,-2,DET,22,-1,ATL,...,34,BOS,519,35,BOS,525,34,BOS,536,33
KC,SF,9,-1,OAK,14,0,SD,18,-1,NaN,...,-27,CLE,547,-26,CLE,560,-27,CLE,565,-26
CLE,LAD,12,-1,SEA,15,-2,AZ,20,-1,TEX,...,-8,KC,478,-9,KC,491,-8,KC,496,-9
TOR,NYY,11,1,DET,16,2,PIT,22,3,PHI,...,9,SEA,551,8,SEA,553,7,SEA,559,6
DET,PHI,7,1,TOR,12,0,NYY,18,-1,BAL,...,-18,CWS,463,-17,CWS,471,-18,CWS,475,-19
TB,BAL,7,-1,ATL,12,0,BOS,21,1,MIN,...,5,CIN,509,4,CIN,514,3,CIN,524,2
ATL,BOS,10,-1,TB,15,-2,MIN,23,-3,NYY,...,12,WSH,561,13,WSH,565,14,WSH,569,15
MIA,NaN,0,0,STL,7,1,HOU,9,0,NaN,...,-6,NYM,491,-5,NYM,496,-6,NYM,498,-5
PHI,DET,7,-1,NYY,12,0,BAL,15,-1,TOR,...,5,STL,555,6,STL,556,7,STL,560,6
SEA,CHC,8,-1,CLE,11,0,COL,13,-1,MIL,...,2,TOR,513,3,TOR,515,4,TOR,521,5
HOU,NYM,5,1,NaN,5,1,MIA,7,2,NaN,...,26,OAK,500,27,OAK,503,26,OAK,509,27
BAL,TB,7,1,PIT,11,2,PHI,14,3,DET,...,-5,LAA,518,-4,LAA,519,-3,LAA,528,-2
MIN,PIT,9,1,BOS,13,0,ATL,21,1,TB,...,10,TEX,558,9,TEX,567,8,TEX,573,9
STL,WSH,29,1,MIA,36,0,NYM,43,1,NaN,...,5,PHI,561,4,PHI,562,3,PHI,566,4
CWS,TEX,7,1,CIN,15,2,OAK,27,1,AZ,...,-5,DET,570,-6,DET,578,-5,DET,582,-4
MIL,SD,4,-1,LAA,14,-2,CHC,19,-1,SEA,...,8,PIT,560,9,PIT,564,8,PIT,572,7
CIN,OAK,5,-1,CWS,13,-2,LAA,20,-3,SD,...,-26,TB,609,-25,TB,614,-24,TB,624,-23
SF,KC,9,1,COL,22,2,TEX,29,1,LAD,...,4,SD,561,3,SD,564,4,SD,576,5
COL,AZ,9,-1,SF,22,-2,SEA,24,-1,OAK,...,-15,AZ,588,-14,AZ,597,-15,AZ,600,-14
PIT,MIN,9,-1,BAL,13,-2,TOR,19,-3,BOS,...,-20,MIL,554,-21,MIL,558,-20,MIL,566,-19
AZ,COL,9,1,SD,17,2,CLE,22,1,CWS,...,-6,COL,561,-7,COL,570,-6,COL,573,-7
SD,MIL,4,1,AZ,12,0,KC,16,1,CIN,...,9,SF,544,10,SF,547,9,SF,559,8
NYM,HOU,5,-1,WSH,12,-2,STL,19,-3,NaN,...,14,MIA,545,13,MIA,550,14,MIA,552,13
NL,NaN,0,0,NaN,0,0,NaN,0,0,NaN,...,0,NaN,0,0,NaN,0,0,NaN,0,0
AL,NaN,0,0,NaN,0,0,NaN,0,0,NaN,...,0,NaN,0,0,NaN,0,0,NaN,0,0
LAA,NaN,0,0,MIL,10,1,CIN,17,2,CHC,...,-7,BAL,520,-8,BAL,521,-9,BAL,530,-10
LAD,CLE,12,1,TEX,20,0,NaN,20,0,SF,...,20,CHC,523,21,CHC,527,22,CHC,538,23

In [89]:
df5 = pd.DataFrame(
    index=df.index
)




sdate = date(2022, 3, 30)
edate = date(2022, 7, 10)

x = 0
while True:
    if (sdate > edate): 
        break
    sDate = sdate.strftime('%Y-%m-%d')
    x+=1
    df[f'opponent ({sDate})'].fillna("n/a", inplace=True)
    df[f'+/- ({sDate})'].fillna(0, inplace=True)

    df5[f'WL ({x})'] = df[f'+/- ({sDate})']
    df5[f'opp ({x}'] = df[f'opponent ({sDate})']
    oppWL = list()
    for x in df[f'opponent ({sDate})']:
        y = df.at[x, f'+/- ({sDate})']
        #oppWL.append(y)
        
    print(oppWL)
    #df5[f'oppWL ({x})'] = oppWL

    break

KeyError: 'n/a'

In [71]:
# prediction, I think the team that is higher in the ranks will a team that is lower in the ranks



p_correct = 0
p_wrong = 0

# find total number of days in season
sdate = date(2022, 3, 30)
edate = date(2022, 7, 10)

# set up loop condition
date_diff = edate - sdate
x = 0

d_curr = sdate

# for each row = team, 
for row in df.index:
    while (x < int(date_diff.days)):
        D_curr = d_curr.strftime('%Y-%m-%d')
        opp = df.loc[row, f'opponent ({D_curr})']
        if (df.loc[opp, f'+/- ({D_curr})'] != None):
            opp_rank = df.loc[opp, f'+/- ({D_curr})']

            team_rank = df.loc[row, f'+/- ({D_curr})']

            d_next = d_curr + datetime.timedelta(days = 1)
            D_next = d_next.strftime('%Y-%m-%d')
            # logic
            if (team_rank > opp_rank):

                next_team_rank = df.loc[row, f'+/- ({D_next})']

                if (next_team_rank > team_rank):
                    p_correct += 1
                else:
                    p_wrong += 1


        # increment date
        d_curr = d_curr + datetime.timedelta(days = 1)
        # increment counter
    
    # reset date
    d_curr = sdate
    # reset counter
    x = 0

KeyError: nan